version: "3.8"

services:
  alipan-tv-token:
    image: ghcr.io/sisheng36/tv-token:latest
    container_name: alipan-tv-token
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
